Answer:
    type: entity
    table: answers
    repositoryClass: Answers
    id:
        id:
            type: uuid
            nullable: false
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: \Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        question:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        displayOrder:
            type: integer
            nullable: false
            column: display_order
            options:
                default: 0
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        note:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        questionConfig:
            type: json
            nullable: true
            column: question_config
            length: null
    manyToOne:
        type:
            targetEntity: QuestionType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type:
                    referencedColumnName: id
        consultation:
            targetEntity: Consultation
            cascade: {  }
            fetch: LAZY
            nullable: false
            mappedBy: null
            inversedBy: null
            joinColumns:
                consultation:
                    referencedColumnName: id
                    onDelete: CASCADE
    lifecycleCallbacks: {  }
