MessageReceipt:
    type: entity
    table: message_receipts
    repositoryClass: MessageReceipts
    id:
        id:
            type: uuid
            nullable: false
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: \Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        dateSeen:
            type: datetime
            nullable: true
            column: date_seen
        review:
            type: boolean
            nullable: false
            length: null
            options:
                default: FALSE
    manyToOne:
        message:
            targetEntity: Message
            cascade: [ persist ]
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                message:
                    referencedColumnName: id
                    onDelete: CASCADE
        recipient:
            targetEntity: Person
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                recipient:
                    referencedColumnName: id
                    onDelete: CASCADE
    lifecycleCallbacks: {  }
