Message:
    type: entity
    table: messages
    repositoryClass: Messages
    id:
        id:
            type: uuid
            nullable: false
            id: true
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: \Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        body:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    manyToOne:
        sender:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sender:
                    referencedColumnName: id
                    onDelete: CASCADE
        parent:
            targetEntity: Message
            cascade: {  }
            fetch: EAGER
            mappedBy: null
            inversedBy: null
            joinColumns:
                parent:
                    referencedColumnName: id
                    onDelete: CASCADE
    oneToMany:
        children:
            orderBy: { 'dateCreated': 'ASC' }
            targetEntity: Message
            fetch: LAZY
            mappedBy: parent
            inversedBy: parent
            orphanRemoval: false
        receipts:
            targetEntity: MessageReceipt
            cascade: [ persist, remove ]
            fetch: LAZY
            mappedBy: message
            inversedBy: message
            orphanRemoval: false
    lifecycleCallbacks: {  }
