Photo:
    type: entity
    table: photos
    repositoryClass: Photos
    entityListeners:
        PhotosListener: {  }
        ModifiableListener: {  }
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        file:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        type:
            targetEntity: PhotoType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type:
                    referencedColumnName: id
        consultation:
            targetEntity: Consultation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                consultation:
                    referencedColumnName: id
                    onDelete: CASCADE
