PhotoType:
    type: entity
    table: photo_types
    repositoryClass: PhotoTypes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        name:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
              fixed: false
        maxUploads:
            type: integer
            nullable: false
            column: max_uploads
            options:
                default: 1
        displayOrder:
            type: integer
            nullable: false
            column: display_order
            options:
                default: 0
    manyToMany:
        products:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: photoTypes
    lifecycleCallbacks: {  }
