Prescription:
    type: entity
    table: prescriptions
    repositoryClass: Prescriptions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        filled:
            type: integer
            nullable: false
            options:
                default: 0
        refills:
            type: integer
            nullable: false
        resupplyAttempts:
            type: integer
            nullable: false
            options:
                default: 0
        instructions:
            type: text
            nullable: false
        dateStart:
            type: datetime
            nullable: false
            column: date_start
        dateEnd:
            type: datetime
            nullable: false
            column: date_end
        dateLastRefilled:
            type: datetime
            nullable: true
            column: date_last_refilled
        status:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: "Active"
        sentReorderNotification:
            type: boolean
            nullable: false
            length: null
            options:
                default: false
    manyToOne:
        consultation:
            targetEntity: Consultation
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                consultation:
                    referencedColumnName: id
                    onDelete: CASCADE
        lineItem:
            targetEntity: LineItem
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_item:
                    referencedColumnName: id
                    onDelete: CASCADE
        creditCard:
            targetEntity: CreditCard
            cascade: [ persist ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                credit_card:
                    referencedColumnName: id
                    onDelete: SET NULL
    lifecycleCallbacks: {  }
