Profession:
  type: entity
  table: professions
  repositoryClass: Professions
  entityListeners:
    PeopleListener: {}
    ModifiableListener: {}
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: false
      id: true
      generator:
        strategy: IDENTITY
  fields:
    title:
      type: string
      nullable: false
      length: null
      options:
        fixed: false
      column: title
    description:
      type: text
      nullable: true
      length: null
      options:
        fixed: false
    dateCreated:
      type: datetime
      nullable: false
      column: date_created
    dateModified:
      type: datetime
      nullable: true
      column: date_modified
  lifecycleCallbacks: {}
