Question:
    type: entity
    table: questions
    repositoryClass: Questions
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateCreated:
            type: datetime
            nullable: false
            column: date_created
        dateModified:
            type: datetime
            nullable: true
            column: date_modified
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        displayOrder:
            type: integer
            nullable: false
            column: display_order
            options:
                default: 0
        config:
            type: json
            nullable: true
            column: config
            length: null
        active:
            type: boolean
            nullable: false
            length: null
            options:
                default: TRUE
    manyToOne:
        type:
            targetEntity: QuestionType
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                type:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    manyToMany:
        products:
            targetEntity: Product
            cascade: {  }
            fetch: LAZY
            mappedBy: questions
            orphanRemoval: false
    lifecycleCallbacks: {  }
