QuestionType:
    type: entity
    table: question_types
    repositoryClass: QuestionTypes
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        template:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
