ALTER TABLE prescriptions DROP FOREIGN KEY FK_E41E1AC3D34A04AD;
DROP INDEX IDX_E41E1AC3D34A04AD ON prescriptions;
ALTER TABLE prescriptions ADD line_item INT DEFAULT NULL, DROP product, CHANGE consultation consultation INT DEFAULT NULL, CHANGE date_modified date_modified DATETIME DEFAULT NULL;
ALTER TABLE prescriptions ADD CONSTRAINT FK_E41E1AC39456D6C7 FOREIGN KEY (line_item) REFERENCES line_items (id) ON DELETE CASCADE;
CREATE INDEX IDX_E41E1AC39456D6C7 ON prescriptions (line_item);
