CREATE TABLE role_permissions (role INT NOT NULL, permission INT NOT NULL, INDEX IDX_1FBA94E657698A6A (role), INDEX IDX_1FBA94E6E04992AA (permission), PRIMARY KEY(role, permission)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE permissions (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE account_permissions (account INT NOT NULL, permission INT NOT NULL, INDEX IDX_FCAA306C7D3656A4 (account), INDEX IDX_FCAA306CE04992AA (permission), PRIMARY KEY(account, permission)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E657698A6A FOREIGN KEY (role) REFERENCES roles (id);
ALTER TABLE role_permissions ADD CONSTRAINT FK_1FBA94E6E04992AA FOREIGN KEY (permission) REFERENCES permissions (id);
ALTER TABLE account_permissions ADD CONSTRAINT FK_FCAA306C7D3656A4 FOREIGN KEY (account) REFERENCES accounts (person);
ALTER TABLE account_permissions ADD CONSTRAINT FK_FCAA306CE04992AA FOREIGN KEY (permission) REFERENCES permissions (id);
ALTER TABLE roles ADD description VARCHAR(255) DEFAULT NULL;
