ALTER TABLE providers ADD npi_number VARCHAR(255) DEFAULT NULL;
ALTER TABLE product_types ADD directions VARCHAR(255) DEFAULT NULL;
ALTER TABLE people ADD gender VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) DEFAULT NULL;
