CREATE TABLE coupon_codes (code VARCHAR(255) NOT NULL, campaign VARCHAR(255) DEFAULT NULL, redeemed TINYINT(1) NOT NULL DEFAULT 0, date_redeemed TIMESTAMP NULL DEFAULT NULL, PRIMARY KEY (`code`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE orders ADD coupon_code VARCHAR(255) DEFAULT NULL;
